# filename: ex046_SK.rq

prefix ab: <http://learningsparql.com/ns/addressbook#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT ?id ?spouse
WHERE
{ 
	?id ab:firstName "Cindy" .
	?id ab:doctor ?spouse . 
}
